language: php
sudo: false
php:
  - 7.1
env:
  global:
  # We need to prefer source to get PHPStan test directory. Otherwise, it is removed from ZIP
  - DEFAULT_COMPOSER_FLAGS="--no-interaction --no-progress --optimize-autoloader --prefer-source"
  - TASK_TESTS=1
  - TASK_TESTS_COVERAGE=0
  - TASK_CS=1
  - TASK_SCA=0
matrix:
  include:
  - php: 7.2
    env: PREFER_LOWEST="" DB=mysql
  - php: 7.1
    env: PREFER_LOWEST="" DB=mysql COVERALLS=true
  - php: 7.1
    env: PREFER_LOWEST="--prefer-lowest" DB=mysql
  - php: 7.1
    env: PREFER_LOWEST="" DB=mariadb
    addons:
      mariadb: '10.0'
  - php: 7.1
    env: PREFER_LOWEST="" DB=postgres PHPUNITFILE="-c phpunit.postgres.xml"
    addons:
      postgresql: "9.6"
    services:
    - postgresql

cache:
  directories:
  - "$HOME/.composer/cache"
before_install:
- travis_retry composer global require $DEFAULT_COMPOSER_FLAGS hirak/prestissimo
install:
- travis_retry composer update $DEFAULT_COMPOSER_FLAGS $PREFER_LOWEST
- composer info -D | sort
script:
- vendor/bin/phpunit
- composer phpstan
- composer cs-check
- vendor/bin/composer-require-checker check --config-file composer-require-checker.json
after_success:
- if [ "$COVERALLS" = "true" ] ; then ./vendor/bin/coveralls -v; fi
